package com.talkweb.demo;

/**
 * @author liuzixuan
 * @date 2020/9/28
 */
public class ToJson {

    public static String s11 = "OPERATING_CONDITION,PREPARATION_TIME,PRODUCTION_TIME,LOWSPEED_TIME,STOP_TIME_I,STOP_TIME_E,STOP_TIME_NONGD,WAIT_TIME,OFF_TIME,RUN_TIME,MAX_RUN_TIME,TOTAL_TIME,REAL_PRODUCTION,THEO_PRODUCTION,MISS_PRODUCTION,LOWSPEED_PRODUCTION,THEO_PRODUCTION_REDUCED,REJECTS,STOP_I_NUMBERS,STOP_E_NUMBERS,STOP_NONGD_NUMBERS,SHIFT_DATE_START,SHIFT_ID,NOMINAL_SPEED";

    public static String s12 = "LABEL_S,STOP_TYPE,EVENT_TIME_START,EVENT_TIME_STOP,EVENT_DURATION";

    public static String s33 = "LABEL_S,STOP_EVENT_START, CURR_DOWNTIME_SEC";

    public static String s44 = "struct@VALUE%FRONT_REJECTS_DUE_TO_SPLICE,struct@VALUE%REAR_REJECTS_DUE_TO_SPLICE,struct@VALUE%FRONT_REJECTS_DUE_TO_REEL_CHANGE,struct@VALUE%REAR_REJECTS_DUE_TO_REEL_CHANGE,struct@VALUE%MANUAL_FRONT_REJECTS,struct@VALUE%MANUAL_REAR_REJECTS,struct@VALUE%FRONT_DRY_SAMPLES,struct@VALUE%REAR_DRY_SAMPLES,struct@VALUE%FRONT_WET_SAMPLES,struct@VALUE%REAR_WET_SAMPLES,struct@VALUE%FRONT_REMOTE_SAMPLES,struct@VALUE%REAR_REMOTE_SAMPLES,struct@VALUE%FRONT_REJ__FOR_DRY_SAMPLING,struct@VALUE%REAR_REJ__FOR_DRY_SAMPLING,struct@VALUE%FRONT_REJECTS_FOR_TOW_SPLICE,struct@VALUE%REAR_REJECTS_FOR_TOW_SPLICE,struct@VALUE%WHITE_FRONT_SAMPLES,struct@VALUE%WHITE_REAR_SAMPLES";

    public static String s55 = "struct@VALUEL%PRESENT_PRODUCTION_SPEED_FPM,struct@VALUEL%PRE_HEATER_TEMPERATURE,struct@VALUEL%FRONT_HEATER_TEMPERATURE,struct@VALUEL%REAR_HEATER_TEMPERATURE,struct@VALUEL%FRONT_TRANSPORT_JET_PRESSURE,struct@VALUEL%REAR_TRANSPORT_JET_PRESSURE,struct@VALUEL%PLASTICIZER_FRONT_UPPER_PUMP_SPEED,struct@VALUEL%PLASTICIZER_FRONT_LOWER_PUMP_SPEED,struct@VALUEL%PLASTICIZER_REAR_UPPER_PUMP_SPEED,struct@VALUE%PLASTICIZER_REAR_LOWER_PUMP_SPEED,struct@VALUE%FRONT_CONVEYOR__TEMPERATURE,struct@VALUE%REAR_CONVEYOR_TEMPERATURE,struct@VALUE%TEMP____FRONT_HEATER,struct@VALUE%TEMP____REAR_HEATER,struct@VALUE%1ST_FRONT_WIDENER_PRESSURE,struct@VALUE%2ND_FRONT_WIDENER_PRESSURE,struct@VALUE%3RD_FRONT_WIDENER_PRESSURE,struct@VALUE%1ST_REAR_WIDENER_PRESSURE,struct@VALUE%2ND_REAR_WIDENER_PRESSURE,struct@VALUE%3RD_REAR_WIDENER_PRESSURE,struct@VALUE%FRONT_UPPER_LINE_PLASTICIZER_PRESSURE,struct@VALUE%FRONT_LOWER_LINE_PLASTICIZER_PRESSURE,struct@VALUE%REAR_UPPER_LINE_PLASTICIZER_PRESSURE,struct@VALUE%REAR_LOWER_LINE_PLASTICIZER_PRESSURE,struct@VALUE%BATCH_01___REAR_PD_SD,struct@VALUE%BATCH_02___REAR_PD_SD,struct@VALUE%BATCH_03___REAR_PD_SD,struct@VALUE%BATCH_01___REAR_PD_AVG,struct@VALUE%BATCH_02___REAR_PD_AVG,struct@VALUE%BATCH_03___REAR_PD_AVG,struct@VALUE%BATCH_01___REAR_WT_SD,struct@VALUE%BATCH_02___REAR_WT_SD,struct@VALUE%BATCH_03___REAR_WT_SD,struct@VALUE%BATCH_01___REAR_WT_AVG,struct@VALUE%BATCH_02___REAR_WT_AVG,struct@VALUE%BATCH_03___REAR_WT_AVG,struct@VALUE%BATCH_01___FRONT_DIAMETER_SD,struct@VALUE%BATCH_02___FRONT_DIAMETER_SD,struct@VALUE%BATCH_03___FRONT_DIAMETER_SD,struct@VALUE%BATCH_01___FRONT_DIAMETER_AVG,struct@VALUE%BATCH_02___FRONT_DIAMETER_AVG,struct@VALUE%BATCH_03___FRONT_DIAMETER_AVG,struct@VALUE%BATCH_01___REAR_OVALITY_SD,struct@VALUE%BATCH_02___REAR_OVALITY_SD,struct@VALUE%BATCH_03___REAR_OVALITY_SD,struct@VALUE%BATCH_01___REAR_OVALITY_AVG,struct@VALUE%BATCH_02___REAR_OVALITY_AVG,struct@VALUE%BATCH_03___REAR_OVALITY_AVG";

    public static String s66 = "struct@CUR_VALUE%SPEED_RATIO_FRONT_STRETCH_INFEED_ROLLERS,struct@CUR_VALUE%SPEED_RATIO__REAR_STRETCH_INFEED_ROLLERS,struct@CUR_VALUE%SPEED_RATIO_FRONT_DELIV__STRETCH_ROLLERS,struct@CUR_VALUE%SPEED_RATIO__REAR_DELIV__STRETCH_ROLLERS,struct@CUR_VALUE%REJECTION_FOR_PAPER_SPLICE,struct@CUR_VALUE%HM_GLUE_WEIGHT_AT_NOMINAL_SPEED,struct@CUR_VALUE%FRONT_PRE_TENSIONER_PRESSURE,struct@CUR_VALUE%REAR_PRE_TENSIONER_PRESSURE";

    public static String s77 = "struct@CUR_VAL%FRONT_PRE-TENSIONER_PRESSURE,struct@CUR_VAL%REAR_PRE-TENSIONER_PRESSURE";

    public static String s88 ="MachineType,MachineCode,DataTime,TotalTime,BV_CurrentVelocity,XX_CurrentVelocity,XX_Status,XX_GoodProduction,XX_RejectedProduction,XX_EliminatingRate,XX_UtilizationRate,XX_TotalField,BV_Status,BV_GoodProduction,BV_RejectedProduction,BV_EliminatingRate,BV_UtilizationRate,BV_TotalField,Param1,Param2,Param3,Param4,Param5,Param6,Param7,Param8,Param9,Param10,Param11,Param12,Param13,Param14,Param15,Param16,Param17,Param18,Param19,Param20,Param21,Param22,Param23,Param24,Param25,Param26,Param27,Param28,Param29,Param30,Param31,Param32,Param33,Param34,Param35,Param36,Param37,Param38,Param39,Param40,Param41,Param42,Param43,XX_MATERIAL_7,XX_MATERIAL_4,XX_MATERIAL_6,XX_MATERIAL_8,BV_MATERIAL_7,BV_MATERIAL_21,BV_MATERIAL_3,Param44,Param45,Param46,Param47,Param48,Param49,Param50,Param51,Param52,Param53,Param54,Param55,Param56,Param57,Param58,Param59";

    public static String s99 = "XX_StartTime,XX_EndTime,XX_Text,XX_DurationTime,BV_StartTime,BV_EndTime,BV_Text,BV_DurationTime";

    public static void main(String args[])
    {
        StringBuffer sb = new StringBuffer();
        String splitStr[] = s99.split(",");
        int size = splitStr.length;

        sb.append("[");

        for (int i=0;i<size;i++)
        {
            if (i==size-1)
            {
                sb.append("{\"tag\":\"").append(splitStr[i]).append("\",").append("\"type\": \"string\"}");
            }
            else
            {
                sb.append("{\"tag\":\"").append(splitStr[i]).append("\",").append("\"type\": \"string\"},");
            }
        }

        sb.append("]");
        System.out.println(sb.toString());

    }
}
